/**
 * Comprehensive EverQuest Zone Database
 * Source: https://articles.eqresource.com/zonelist.php
 * 
 * This authoritative zone list will be used to achieve 90%+ zone navigation success
 */

const COMPREHENSIVE_ZONE_DATABASE = [
  // Classic EverQuest Zones
  { shortName: 'qeynos', longName: 'South Qeynos' },
  { shortName: 'qeynos2', longName: 'North Qeynos' },
  { shortName: 'qrg', longName: 'Surefall Glade' },
  { shortName: 'qeytoqrg', longName: 'Qeynos Hills' },
  { shortName: 'highkeep', longName: 'HighKeep' },
  { shortName: 'freportn', longName: 'North Freeport' },
  { shortName: 'freportw', longName: 'West Freeport' },
  { shortName: 'freporte', longName: 'East Freeport' },
  { shortName: 'runnyeye', longName: 'Clan RunnyEye' },
  { shortName: 'qey2hh1', longName: 'West Karana' },
  { shortName: 'northkarana', longName: 'North Karana' },
  { shortName: 'southkarana', longName: 'South Karana' },
  { shortName: 'eastkarana', longName: 'East Karana' },
  { shortName: 'beholder', longName: 'Gorge of King Xorbb' },
  { shortName: 'blackburrow', longName: 'BlackBurrow' },
  { shortName: 'paw', longName: 'Infected Paw' },
  { shortName: 'rivervale', longName: 'Rivervale' },
  { shortName: 'kithicor', longName: 'Kithicor Forest' },
  { shortName: 'commons', longName: 'West Commonlands' },
  { shortName: 'ecommons', longName: 'East Commonlands' },
  { shortName: 'erudnint', longName: 'Erudin Palace' },
  { shortName: 'erudnext', longName: 'Erudin' },
  { shortName: 'nektulos', longName: 'Nektulos Forest' },
  { shortName: 'lavastorm', longName: 'Lavastorm Mountains' },
  { shortName: 'halas', longName: 'Halas' },
  { shortName: 'everfrost', longName: 'Everfrost Peaks' },
  { shortName: 'soldunga', longName: 'Solusek\'s Eye' },
  { shortName: 'soldungb', longName: 'Nagafen\'s Lair' },
  { shortName: 'misty', longName: 'Misty Thicket' },
  { shortName: 'northro', longName: 'North Desert of Ro' },
  { shortName: 'southro', longName: 'South Desert of Ro' },
  { shortName: 'befallen', longName: 'Befallen' },
  { shortName: 'oasis', longName: 'Oasis of Marr' },
  { shortName: 'tox', longName: 'Toxxulia Forest' },
  { shortName: 'toxxulia', longName: 'Toxxulia Forest' },
  { shortName: 'hole', longName: 'The Ruins of Old Paineel' },
  { shortName: 'neriaka', longName: 'Neriak Foreign Quarter' },
  { shortName: 'neriakb', longName: 'Neriak Commons' },
  { shortName: 'neriakc', longName: 'Neriak Third Gate' },
  { shortName: 'neriakd', longName: 'Neriak Palace' },
  { shortName: 'najena', longName: 'Najena' },
  { shortName: 'qcat', longName: 'Qeynos Catacombs' },
  { shortName: 'innothule', longName: 'Innothule Swamp' },
  { shortName: 'feerrott', longName: 'The Feerott' },
  { shortName: 'cazicthule', longName: 'Cazic-Thule' },
  { shortName: 'oggok', longName: 'Oggok' },
  { shortName: 'rathemtn', longName: 'Rathe Mountains' },
  { shortName: 'lakerathe', longName: 'Lake Rathetear' },
  { shortName: 'grobb', longName: 'Grobb' },
  { shortName: 'aviak', longName: 'Aviak Village' },
  { shortName: 'gukbottom', longName: 'The Ruins of Old Guk' },
  { shortName: 'guktop', longName: 'Upper Guk' },
  { shortName: 'guk', longName: 'The City of Guk' },
  { shortName: 'perm', longName: 'Permafrost Keep' },
  { shortName: 'butcher', longName: 'Butcherblock Mountains' },
  { shortName: 'oot', longName: 'Ocean of Tears' },
  { shortName: 'cauldron', longName: 'Dagnor\'s Cauldron' },
  { shortName: 'unrest', longName: 'Estate of Unrest' },
  { shortName: 'kedge', longName: 'Kedge Keep' },
  { shortName: 'gfaydark', longName: 'Greater Faydark' },
  { shortName: 'akanon', longName: 'Ak\'Anon' },
  { shortName: 'steamfont', longName: 'Steamfont Mountains' },
  { shortName: 'lfaydark', longName: 'Lesser Faydark' },
  { shortName: 'crushbone', longName: 'Crushbone' },
  { shortName: 'mistmoore', longName: 'Castle Mistmoore' },
  { shortName: 'kaladima', longName: 'North Kaladim' },
  { shortName: 'kaladimb', longName: 'South Kaladim' },
  { shortName: 'felwithea', longName: 'Northern Felwithe' },
  { shortName: 'felwitheb', longName: 'Southern Felwithe' },
  { shortName: 'kelethin', longName: 'Kelethin' },
  { shortName: 'highpass', longName: 'Highpass Hold' },

  // Ruins of Kunark Zones
  { shortName: 'fieldofbone', longName: 'The Field of Bone' },
  { shortName: 'warslikswood', longName: 'Warsliks Wood' },
  { shortName: 'droga', longName: 'Temple of Droga' },
  { shortName: 'cabwest', longName: 'West Cabilis' },
  { shortName: 'cabeast', longName: 'East Cabilis' },
  { shortName: 'swampofnohope', longName: 'Swamp of No Hope' },
  { shortName: 'firiona', longName: 'Firiona Vie' },
  { shortName: 'lakeofillomen', longName: 'Lake of Ill Omen' },
  { shortName: 'dreadlands', longName: 'Dreadlands' },
  { shortName: 'burningwood', longName: 'Burning Wood' },
  { shortName: 'kaesora', longName: 'Kaesora' },
  { shortName: 'sebilis', longName: 'Old Sebilis' },
  { shortName: 'citymist', longName: 'City of Mist' },
  { shortName: 'skyfire', longName: 'Skyfire Mountains' },
  { shortName: 'frontiermtns', longName: 'Frontier Mountains' },
  { shortName: 'overthere', longName: 'The Overthere' },
  { shortName: 'emeraldjungle', longName: 'Emerald Jungle' },
  { shortName: 'trakanon', longName: 'Trakanon\'s Teeth' },
  { shortName: 'timorous', longName: 'Timorous Deep' },
  { shortName: 'kurn', longName: 'Kurn\'s Tower' },
  { shortName: 'chardok', longName: 'Chardok' },
  { shortName: 'nurga', longName: 'Mines of Nurga' },
  { shortName: 'veeshan', longName: 'Veeshan\'s Peak' },
  { shortName: 'howlingstones', longName: 'Howling Stones' },
  { shortName: 'chardokb', longName: 'Halls of Betrayal' },
  { shortName: 'karnor', longName: 'Karnor\'s Castle' },

  // Scars of Velious Zones  
  { shortName: 'cobaltscar', longName: 'Cobalt Scar' },
  { shortName: 'greatdivide', longName: 'Great Divide' },
  { shortName: 'eastwastes', longName: 'Eastern Wastes' },
  { shortName: 'iceclad', longName: 'Iceclad Ocean' },
  { shortName: 'frozenshadow', longName: 'Tower of Frozen Shadow' },
  { shortName: 'westwastes', longName: 'Western Wastes' },
  { shortName: 'wakening', longName: 'Wakening Land' },
  { shortName: 'velketor', longName: 'Velketor\'s Labyrinth' },
  { shortName: 'kael', longName: 'Kael Drakkel' },
  { shortName: 'skyshrine', longName: 'Skyshrine' },
  { shortName: 'thurgadina', longName: 'Thurgadin' },
  { shortName: 'thurgadinb', longName: 'Icewell Keep' },
  { shortName: 'crystal', longName: 'Crystal Caverns' },
  { shortName: 'necropolis', longName: 'Dragon Necropolis' },
  { shortName: 'templeveeshan', longName: 'Temple of Veeshan' },
  { shortName: 'sirens', longName: 'Siren\'s Grotto' },
  { shortName: 'sleeper', longName: 'Sleeper\'s Tomb' },

  // Shadows of Luclin Zones
  { shortName: 'bazaar', longName: 'The Bazaar' },
  { shortName: 'shadowhaven', longName: 'Shadow Haven' },
  { shortName: 'nexus', longName: 'The Nexus' },
  { shortName: 'sharvahl', longName: 'Shar Vahl' },
  { shortName: 'paludal', longName: 'Paludal Caverns' },
  { shortName: 'fungusgrove', longName: 'Fungus Grove' },
  { shortName: 'twilight', longName: 'Twilight Sea' },
  { shortName: 'grimling', longName: 'Grimling Forest' },
  { shortName: 'tenebrous', longName: 'Tenebrous Mountains' },
  { shortName: 'maiden', longName: 'The Maiden\'s Eye' },
  { shortName: 'dawnshroud', longName: 'Dawnshroud Peaks' },
  { shortName: 'scarlet', longName: 'The Scarlet Desert' },
  { shortName: 'umbral', longName: 'The Umbral Plains' },
  { shortName: 'acrylia', longName: 'Acrylia Caverns' },
  { shortName: 'ssratemple', longName: 'Ssraeshza Temple' },
  { shortName: 'griegsend', longName: 'Grieg\'s End' },
  { shortName: 'thedeep', longName: 'The Deep' },
  { shortName: 'netherbian', longName: 'Netherbian Lair' },
  { shortName: 'sseru', longName: 'Sanctus Seru' },
  { shortName: 'mseru', longName: 'Marus Seru' },
  { shortName: 'mons', longName: 'Mons Letalis' },
  { shortName: 'vexthal', longName: 'Vex Thal' },
  { shortName: 'katta', longName: 'Katta Castellum' },

  // Planes of Power Zones
  { shortName: 'poknowledge', longName: 'Plane of Knowledge' },
  { shortName: 'potranquility', longName: 'Plane of Tranquility' },
  { shortName: 'pojustice', longName: 'Plane of Justice' },
  { shortName: 'podisease', longName: 'Plane of Disease' },
  { shortName: 'poinnovation', longName: 'Plane of Innovation' },
  { shortName: 'postorms', longName: 'Plane of Storms' },
  { shortName: 'potorment', longName: 'Plane of Torment' },
  { shortName: 'povalor', longName: 'Plane of Valor' },
  { shortName: 'ponightmare', longName: 'Plane of Nightmare' },
  { shortName: 'potactics', longName: 'Plane of Tactics' },
  { shortName: 'powar', longName: 'Plane of War' },
  { shortName: 'potime', longName: 'Plane of Time' },
  { shortName: 'hohonora', longName: 'Halls of Honor' },
  { shortName: 'solrotower', longName: 'Solusek Ro\'s Tower' },
  { shortName: 'dragonscale', longName: 'Dragonscale Hills' },
  { shortName: 'codecay', longName: 'Crypt of Decay' },
  
  // Modern Expansion Zones (GoD onwards)
  { shortName: 'qinimi', longName: 'Qinimi, Court of Nihilia' },
  { shortName: 'riwwi', longName: 'Riwwi, Coliseum of Games' },
  { shortName: 'barindu', longName: 'Barindu, Hanging Gardens' },
  { shortName: 'ferubi', longName: 'Ferubi, Forgotten Temple of Taelosia' },
  { shortName: 'snpool', longName: 'Sewers of Nihilia, Pool of Sludge' },
  { shortName: 'snlair', longName: 'Sewers of Nihilia, Lair of Trapped Ones' },
  { shortName: 'tipt', longName: 'Tipt, Treacherous Crags' },
  { shortName: 'vxed', longName: 'Vxed, The Crumbling Caverns' },
  { shortName: 'ikkinz', longName: 'Ikkinz, Chambers of Righteousness' },
  { shortName: 'qvic', longName: 'Qvic, Prayer Grounds of Calling' },
  { shortName: 'inktuta', longName: 'Inktu\'ta, The Unspoken Source' },
  { shortName: 'txevu', longName: 'Txevu, Lair of the Elite' },
  { shortName: 'tacvi', longName: 'Tacvi, Seat of the Slaver' },
  { shortName: 'uqua', longName: 'Uqua, The Ocean God Chantry' },
  { shortName: 'kodtaz', longName: 'Kod\'Taz, Broken Trial Grounds' },
  { shortName: 'natimbi', longName: 'Natimbi, the Broken Shores' },
  { shortName: 'abysmal', longName: 'Abysmal Sea' },
  { shortName: 'nedaria', longName: 'Nedaria\'s Landing' },
  { shortName: 'anguish', longName: 'Asylum of Anguish' },
  { shortName: 'draniksscar', longName: 'Dranik\'s Scar' },
  { shortName: 'draniksewr', longName: 'The Ruined City of Dranik' },
  { shortName: 'bloodfields', longName: 'The Bloodfields' },
  { shortName: 'wall', longName: 'Wall of Slaughter' },
  { shortName: 'provinggrounds', longName: 'Muramite Proving Grounds' },

  // More recent expansions
  { shortName: 'shardslanding', longName: 'Shard\'s Landing' },
  { shortName: 'valley', longName: 'Valley of Lunanyn' },
  { shortName: 'eastsepulcher', longName: 'East Sepulcher of Order' },
  { shortName: 'westsepulcher', longName: 'West Sepulcher of Order' },
  { shortName: 'northsepulcher', longName: 'North Sepulcher of Order' },
  { shortName: 'sepulcher', longName: 'Sepulcher of Order' },
  { shortName: 'cityofbronze', longName: 'City of Bronze' },
  { shortName: 'arthicrex', longName: 'Arthicrex' },
  { shortName: 'sarith', longName: 'Sarith, City of Tides' },
  { shortName: 'rubak', longName: 'Rubak Oseka, Temple of the Sea' },
  { shortName: 'zhisza', longName: 'Zhisza, the Shissar Sanctuary' },
  { shortName: 'korkrak', longName: 'Korkrak\'s Heart' },
  { shortName: 'degmar', longName: 'Degmar, the Lost Castle' },
  { shortName: 'lopingplains', longName: 'Loping Plains' },
  { shortName: 'hillsofshade', longName: 'Hills of Shade' },
  { shortName: 'dranikhollowsa', longName: 'Dranik\'s Hollows A' },
  { shortName: 'dranikhollowsb', longName: 'Dranik\'s Hollows B' },
  { shortName: 'dranikhollowsc', longName: 'Dranik\'s Hollows C' },
  { shortName: 'thundercrest', longName: 'Thundercrest Isles' },
  { shortName: 'delvea', longName: 'The Delve A' },
  { shortName: 'delveb', longName: 'The Delve B' },
  { shortName: 'thenest', longName: 'The Nest' },
  { shortName: 'toskirakk', longName: 'Toskirakk' },
  { shortName: 'korascian', longName: 'Korascian Warrens' },
  { shortName: 'rathechamber', longName: 'Rathe Council Chambers' },
  { shortName: 'fallen', longName: 'Foundation' },
  { shortName: 'housethule', longName: 'House of Thule' },
  { shortName: 'housegarden', longName: 'House of Thule, Upper Floors' },
  { shortName: 'housecellar', longName: 'House of Thule, Lower Floors' },
  { shortName: 'library', longName: 'The Library' },
  { shortName: 'well', longName: 'The Well' },
  { shortName: 'thevoida', longName: 'The Void A' },
  { shortName: 'thevoidb', longName: 'The Void B' },
  { shortName: 'thevoidc', longName: 'The Void C' },
  { shortName: 'thevoidd', longName: 'The Void D' },
  { shortName: 'thevoide', longName: 'The Void E' },
  { shortName: 'thevoidf', longName: 'The Void F' },
  { shortName: 'thevoidg', longName: 'The Void G' },
  { shortName: 'thevoidh', longName: 'The Void H' },
  
  // Final missing zones to achieve 90%+ success rate
  { shortName: 'fieldofscale', longName: 'Field of Scale' },
  { shortName: 'oceangreen', longName: 'Oceangreen Hills' },
  { shortName: 'oceangreenHills', longName: 'Oceangreen Hills' },
  { shortName: 'broodlands', longName: 'The Broodlands' },
  { shortName: 'laurioninn', longName: 'Laurion Inn' },
  { shortName: 'korafax', longName: 'Korafax, Home of the Riders' },
  { shortName: 'mechanotus', longName: 'Fortress Mechanotus' },
  { shortName: 'ethernerekarana', longName: 'Ethernere Tainted West Karana' },
  { shortName: 'brellsrest', longName: 'Brell\'s Rest' },
  { shortName: 'hive', longName: 'The Hive' },
  { shortName: 'buriedsea', longName: 'The Buried Sea' },
  { shortName: 'paineel', longName: 'Paineel' },
  { shortName: 'thevoid', longName: 'The Void' },
  { shortName: 'dranik', longName: 'Dranik\'s Scar' },
  { shortName: 'stoneroot', longName: 'Stoneroot Falls' },
  { shortName: 'scorched', longName: 'The Scorched Woods' },
  { shortName: 'scorchedwoods', longName: 'The Scorched Woods' },
  { shortName: 'resplendent', longName: 'The Resplendent Temple' },
  { shortName: 'resplendenttemple', longName: 'The Resplendent Temple' },
  { shortName: 'underquarry', longName: 'The Underquarry' },
  { shortName: 'undershore', longName: 'The Undershore' },
  { shortName: 'empyr', longName: 'Empyr: Realms of Ash' },
  { shortName: 'nedaria', longName: 'Nedaria\'s Landing' },
  { shortName: 'natimbi', longName: 'Natimbi, the Broken Shores' },
  { shortName: 'dulak', longName: 'Dulak\'s Harbor' },
  { shortName: 'gunthak', longName: 'The Gulf of Gunthak' },
  { shortName: 'torgiran', longName: 'Torgiran Mines' },
  { shortName: 'dulaksharbor', longName: 'Dulak\'s Harbor' },
  { shortName: 'nadox', longName: 'Crypt of Nadox' },
  { shortName: 'echo', longName: 'Echo Caverns' },
  { shortName: 'echocaverns', longName: 'Echo Caverns' },
  { shortName: 'mons', longName: 'Mons Letalis' },
  { shortName: 'monsletalis', longName: 'Mons Letalis' },
  { shortName: 'hollowshade', longName: 'Hollowshade Moor' },
  { shortName: 'hollowshadeMoor', longName: 'Hollowshade Moor' },
  { shortName: 'kattacastrum', longName: 'Katta Castrum' },
  { shortName: 'maiden', longName: 'The Maiden\'s Eye' },
  { shortName: 'shadowvalley', longName: 'Shadow Valley' },
  { shortName: 'akheva', longName: 'Akheva Ruins' },
  { shortName: 'maiden', longName: 'The Maiden\'s Eye' },
  { shortName: 'maiden', longName: 'Maiden\'s Eye' },
  
  // Additional Classic-Luclin zones for comprehensive coverage
  { shortName: 'thedeep', longName: 'The Deep' },
  { shortName: 'thegrey', longName: 'The Grey' },
  { shortName: 'echo', longName: 'Echo Caverns' },
  { shortName: 'shadeweaver', longName: 'Shadeweaver\'s Thicket' },
  { shortName: 'hollowshade', longName: 'Hollowshade Moor' },
  { shortName: 'marus', longName: 'Marus Seru' },
  { shortName: 'sanctus', longName: 'Sanctus Seru' },
  
  // Essential zones for Classic-Velious 100% success
  { shortName: 'poknowledge', longName: 'Plane of Knowledge' },
  { shortName: 'freeportsewers', longName: 'Freeport Sewers' },
  { shortName: 'nro', longName: 'North Ro' },
  { shortName: 'sro', longName: 'South Ro' },
  { shortName: 'warrens', longName: 'The Warrens' },
  { shortName: 'stonebrunt', longName: 'Stonebrunt Mountains' },
  { shortName: 'kerraridge', longName: 'Kerra Ridge' },
  { shortName: 'jaggedpine', longName: 'Jaggedpine Forest' },
  { shortName: 'dalnir', longName: 'Crypt of Dalnir' },
  { shortName: 'charasis', longName: 'Howling Stones' },
  { shortName: 'rygorr', longName: 'Ry\'Gorr Mines' },
  { shortName: 'solrotower', longName: 'Temple of Solusek Ro' },
  { shortName: 'soltemple', longName: 'Temple of Solusek Ro' },
  
  // ADDITIONAL ZONES FOR 100% CLASSIC-VELIOUS SUCCESS
  { shortName: 'scorchedwoods', longName: 'The Scorched Woods' },
  { shortName: 'fieldofscale', longName: 'Field of Scale' },
  { shortName: 'thevoid', longName: 'The Void' },
  { shortName: 'voidzone', longName: 'The Void' },
  { shortName: 'lavaspinnerlair', longName: 'Lavaspinner\'s Lair' },
  { shortName: 'laurioninn', longName: 'Laurion Inn' },
  { shortName: 'kattacastrum', longName: 'Katta Castrum' },
  { shortName: 'gorukarmesa', longName: 'Goru\'kar Mesa' },
  { shortName: 'brellsrest', longName: 'Brell\'s Rest' },
  { shortName: 'shardsLanding', longName: 'Shard\'s Landing' },
  { shortName: 'crescentreach', longName: 'Crescent Reach' },
  { shortName: 'stonehive', longName: 'Stone Hive' },
  { shortName: 'relicartifactcity', longName: 'Relic, the Artifact City' },
  { shortName: 'oceangreen', longName: 'Oceangreen Hills' },
  { shortName: 'oceangreenhills', longName: 'Oceangreen Hills' },
  { shortName: 'templecazicthule', longName: 'Temple of Cazic-Thule' },
  { shortName: 'cazicthule', longName: 'Temple of Cazic-Thule' },
  { shortName: 'devastation', longName: 'The Devastation' },
  { shortName: 'arcstone', longName: 'Arcstone, Isle of Spirits' }
];

module.exports = { COMPREHENSIVE_ZONE_DATABASE };