[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["python -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python app.py"