[variables]
PYTHONPATH = "."

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Flask app ready'"]

[start]
cmd = "python app.py"